In [1]:
import pandas as pd

In [2]:
data = pd.read_csv ("/home/dung/machinelearning/CNN/OCSVM/bt_dataset_t3.csv")

In [3]:
data.head (5)

,Image,Mean,Variance,Standard Deviation,Entropy,Skewness,Kurtosis,Contrast,Energy,ASM,Homogeneity,Dissimilarity,Correlation,Coarseness,PSNR,SSIM,MSE,DC,Target
0,Image1,23.448517,2538.985627,50.388348,0.651174,1.984202,5.421042,181.467713,0.781557,0.610831,0.847033,2.765411,0.968576,7.458341e-155,97.974630,0.777011,0.171163,0.303989,1
1,Image2,4.398331,834.853030,28.893823,0.953532,6.495203,43.349355,76.745886,0.972770,0.946281,0.980762,0.548605,0.959751,7.458341e-155,110.346597,0.977953,0.009913,0.839019,1
2,Image3,3.244263,642.059166,25.338886,0.966065,7.772860,61.756034,81.752406,0.980161,0.960715,0.985066,0.540411,0.944259,7.458341e-155,112.266298,0.985362,0.006372,0.849775,1
3,Image4,8.511353,1126.214187,33.559115,0.868765,3.763142,15.107579,362.291213,0.921786,0.849690,0.949295,2.765725,0.859027,7.458341e-155,101.955792,0.881015,0.068437,0.000000,0
4,Image5,21.000793,2235.316978,47.279139,0.684724,1.936029,4.722343,312.439226,0.804184,0.646711,0.880301,3.006660,0.938572,7.458341e-155,97.639870,0.766308,0.184878,0.000000,0

In [4]:
data.isnull ()

,Image,Mean,Variance,Standard Deviation,Entropy,Skewness,Kurtosis,Contrast,Energy,ASM,Homogeneity,Dissimilarity,Correlation,Coarseness,PSNR,SSIM,MSE,DC,Target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1639,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1640,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1641,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1642,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1643,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
data.notna

<bound method DataFrame.notna of           Image       Mean     Variance  Standard Deviation   Entropy  \
0        Image1  23.448517  2538.985627           50.388348  0.651174
1        Image2   4.398331   834.853030           28.893823  0.953532
2        Image3   3.244263   642.059166           25.338886  0.966065
3        Image4   8.511353  1126.214187           33.559115  0.868765
4        Image5  21.000793  2235.316978           47.279139  0.684724
...         ...        ...          ...                 ...       ...
1639  Image1640   0.199158    26.491880            5.147026  0.996341
1640  Image1641   6.885025   802.478515           28.328052  0.878419
1641  Image1642   1.828186   230.107684           15.169301  0.966424
1642  Image1643   0.061630     8.029570            2.833650  0.998740
1643  Image1644   0.718506    91.460572            9.563502  0.986739

       Skewness     Kurtosis    Contrast    Energy       ASM  Homogeneity  \
0      1.984202     5.421042  181.467713  0.781557  0.610831     0.847033
1      6.495203    43.349355   76.745886  0.972770  0.946281     0.980762
2      7.772860    61.756034   81.752406  0.980161  0.960715     0.985066
3      3.763142    15.107579  362.291213  0.921786  0.849690     0.949295
4      1.936029     4.722343  312.439226  0.804184  0.646711     0.880301
...         ...          ...         ...       ...       ...          ...
1639  25.826301   668.181974   14.797350  0.997873  0.995751     0.998476
1640   3.939967    16.456794  266.135425  0.927687  0.860602     0.951086
1641   8.218790    68.539071  105.172699  0.980371  0.961128     0.985590
1642  45.985085  2116.600001    6.431276  0.999268  0.998536     0.999401
1643  13.268497   177.139371   42.023257  0.992277  0.984614     0.994537

      Dissimilarity  Correlation     Coarseness        PSNR      SSIM  \
0          2.765411     0.968576  7.458341e-155   97.974630  0.777011
1          0.548605     0.959751  7.458341e-155  110.346597  0.977953
2          0.540411     0.944259  7.458341e-155  112.266298  0.985362
3          2.765725     0.859027  7.458341e-155  101.955792  0.881015
4          3.006660     0.938572  7.458341e-155   97.639870  0.766308
...             ...          ...            ...         ...       ...
1639       0.113842     0.755553  7.458341e-155   75.822768  0.995798
1640       2.303173     0.854682  7.458341e-155   60.126401  0.886831
1641       0.863250     0.799919  7.458341e-155   66.013000  0.964771
1642       0.050628     0.649484  7.458341e-155   80.821412  0.998316
1643       0.341771     0.798902  7.458341e-155   70.076550  0.985988

           MSE        DC  Target
0     0.171163  0.303989       1
1     0.009913  0.839019       1
2     0.006372  0.849775       1
3     0.068437  0.000000       0
4     0.184878  0.000000       0
...        ...       ...     ...
1639  0.001701  0.000000       0
1640  0.063160  0.000000       0
1641  0.016285  0.000000       0
1642  0.000538  0.000000       0
1643  0.006389  0.000000       0

[1644 rows x 19 columns]>

In [6]:
data.shape

(1644, 19)

In [14]:

from sklearn.preprocessing import StandardScaler

train_size = int ( len(data)*0.8)
test_size = len(data )-train_size 
labels = data['Target']
data_new = data.drop(columns = ['Target','Image'])

print (data_new.columns )
scaler = StandardScaler () 
data_scaled = pd.DataFrame(scaler.fit_transform(data_new), columns=data_new.columns )
data_normal =data_scaled[labels==0]
data_tumor = data_scaled[labels==1]

Index(['Mean', 'Variance', 'Standard Deviation', 'Entropy', 'Skewness',
       'Kurtosis', 'Contrast', 'Energy', 'ASM', 'Homogeneity', 'Dissimilarity',
       'Correlation', 'Coarseness', 'PSNR', 'SSIM', 'MSE', 'DC'],
      dtype='object')

ValueError: Input X contains infinity or a value too large for dtype('float64').

Index(['Image', 'Mean', 'Variance', 'Standard Deviation', 'Entropy',
       'Skewness', 'Kurtosis', 'Contrast', 'Energy', 'ASM', 'Homogeneity',
       'Dissimilarity', 'Correlation', 'Coarseness', 'PSNR', 'SSIM', 'MSE',
       'DC', 'Target'],
      dtype='object')