In [1]:
import pandas as pd 
import numpy as np

In [2]:
data= pd.read_csv("/home/dung/machinelearning/CNN/k_MEAN/players_22.csv")

/tmp/ipykernel_13252/1077848665.py:1: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  data= pd.read_csv("/home/dung/machinelearning/CNN/k_MEAN/players_22.csv")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19239 entries, 0 to 19238
Columns: 110 entries, sofifa_id to nation_flag_url
dtypes: float64(16), int64(44), object(50)
memory usage: 16.1+ MB

In [4]:
data.notnull()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,False,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,False,True
19235,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,False,True
19236,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,False,True
19237,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,False,True
19238,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,False,True

In [5]:
data.head(5)

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png

In [6]:
data.columns

Index(['sofifa_id', 'player_url', 'short_name', 'long_name',
       'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur',
       'age',
       ...
       'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url',
       'club_flag_url', 'nation_logo_url', 'nation_flag_url'],
      dtype='object', length=110)

In [7]:
columns =["pace", "shooting", "passing", "dribbling", "defending", "physic"]
data[columns ]. head (5)

   pace  shooting  passing  dribbling  defending  physic
0  85.0      92.0     91.0       95.0       34.0    65.0
1  78.0      92.0     79.0       86.0       44.0    82.0
2  87.0      94.0     80.0       88.0       34.0    75.0
3  91.0      83.0     86.0       94.0       37.0    63.0
4  76.0      86.0     93.0       88.0       64.0    78.0

In [8]:
data = data[columns]

In [10]:
data

       pace  shooting  passing  dribbling  defending  physic
0      85.0      92.0     91.0       95.0       34.0    65.0
1      78.0      92.0     79.0       86.0       44.0    82.0
2      87.0      94.0     80.0       88.0       34.0    75.0
3      91.0      83.0     86.0       94.0       37.0    63.0
4      76.0      86.0     93.0       88.0       64.0    78.0
...     ...       ...      ...        ...        ...     ...
19234  58.0      35.0     46.0       48.0       42.0    49.0
19235  59.0      39.0     50.0       46.0       41.0    51.0
19236  60.0      37.0     45.0       49.0       41.0    52.0
19237  68.0      46.0     36.0       48.0       15.0    42.0
19238  68.0      38.0     45.0       48.0       36.0    48.0

[19239 rows x 6 columns]

In [12]:
data.notna()

       pace  shooting  passing  dribbling  defending  physic
0      True      True     True       True       True    True
1      True      True     True       True       True    True
2      True      True     True       True       True    True
3      True      True     True       True       True    True
4      True      True     True       True       True    True
...     ...       ...      ...        ...        ...     ...
19234  True      True     True       True       True    True
19235  True      True     True       True       True    True
19236  True      True     True       True       True    True
19237  True      True     True       True       True    True
19238  True      True     True       True       True    True

[19239 rows x 6 columns]

In [13]:
import matplotlib.pyplot as plt

In [14]:
for cols in columns : 
    data[cols] = (data[cols]-data[cols].min())/(data[cols].max()-data[cols].min() )

In [15]:
data

           pace  shooting   passing  dribbling  defending    physic
0      0.826087  0.973684  0.970588   1.000000   0.259740  0.590164
1      0.724638  0.973684  0.794118   0.867647   0.389610  0.868852
2      0.855072  1.000000  0.808824   0.897059   0.259740  0.754098
3      0.913043  0.855263  0.897059   0.985294   0.298701  0.557377
4      0.695652  0.894737  1.000000   0.897059   0.649351  0.803279
...         ...       ...       ...        ...        ...       ...
19234  0.434783  0.223684  0.308824   0.308824   0.363636  0.327869
19235  0.449275  0.276316  0.367647   0.279412   0.350649  0.360656
19236  0.463768  0.250000  0.294118   0.323529   0.350649  0.377049
19237  0.579710  0.368421  0.161765   0.308824   0.012987  0.213115
19238  0.579710  0.263158  0.294118   0.308824   0.285714  0.311475

[19239 rows x 6 columns]

In [23]:

def gen_centroids ( data, k ) : 
    centroids =[]
    for i in range (k ) : 
      

        centroid= data.apply(lambda x : float(x.sample() ))
        centroids.append(centroid )
    return pd.concat(centroids, axis = 1 )

In [24]:
centroids = gen_centroids(data,5)

/tmp/ipykernel_13252/185428867.py:6: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  centroid= data.apply(lambda x : float(x.sample() ))

In [25]:
centroids.head()

                  0         1         2         3         4
pace       0.536232  0.144928       NaN  0.753623  0.420290
shooting   0.434211  0.552632  0.394737  0.486842  0.381579
passing    0.441176  0.441176  0.588235  0.573529       NaN
dribbling  0.705882  0.602941  0.235294  0.514706  0.573529
defending  0.662338       NaN  0.714286  0.155844  0.636364

In [29]:
centroids = centroids.fillna( centroids.mean() )
centroids.head ()

                  0         1         2         3         4
pace       0.536232  0.144928  0.524215  0.753623  0.420290
shooting   0.434211  0.552632  0.394737  0.486842  0.381579
passing    0.441176  0.441176  0.588235  0.573529  0.474484
dribbling  0.705882  0.602941  0.235294  0.514706  0.573529
defending  0.662338  0.435419  0.714286  0.155844  0.636364

In [31]:
distances = centroids.apply( lambda x: np.sqrt(((data-x)**2).sum(axis =1 )))

In [32]:
distances

              0         1         2         3         4
0      1.016852  1.064897  1.171991  0.836003  1.066666
1      0.980003  0.947602  0.977517  0.850878  0.975212
2      1.015268  1.028851  1.083196  0.800482  1.041430
3      0.919185  1.034010  1.100479  0.739176  0.983879
4      0.956929  1.000105  0.950925  0.968129  0.957120
...         ...       ...       ...       ...       ...
19234  0.573309  0.559432  0.611361  0.572382  0.445094
19235  0.578036  0.540214  0.556754  0.522158  0.437576
19236  0.570896  0.550940  0.590035  0.541246  0.442873
19237  0.814782  0.784483  0.953357  0.546245  0.777057
19238  0.599162  0.647098  0.661924  0.469067  0.517120

[19239 rows x 5 columns]

In [37]:
labels = distances.idxmin ( axis = 1 )

In [38]:
labels

0        3
1        3
2        3
3        3
4        2
        ..
19234    4
19235    4
19236    4
19237    3
19238    3
Length: 19239, dtype: int64

In [43]:
new_centroids = data.groupby(labels).mean ()

In [44]:
new_centroids.head ()

       pace  shooting   passing  dribbling  defending    physic
0  0.707795  0.577667  0.639666   0.697297   0.604001  0.469118
1  0.313467  0.616587  0.490627   0.533412   0.373232  0.650392
2  0.529055  0.348057  0.449695   0.453448   0.668029  0.718026
3  0.684797  0.579510  0.484363   0.585961   0.247417  0.497770
4  0.558528  0.389265  0.480928   0.518466   0.571580  0.527834

In [56]:
class k_mean : 
    def __init__ ( self, k : int , interation : int  ) : 
        self.k = k 
        self.data= data
        self.interation = interation 
    def gen_centroids ( self  , data ) : 
        centroids = []
        for i in range  ( self.k):
            centroid = self.data.apply(lambda x : float (x.sample()))
            centroids.append(centroid)
        return  pd.concat(centroids, axis=1)
    def forward ( self, data   ):
        centroids = self.gen_centroids(self.data)
        labels = [] 
        for i in range (self.interation )  :
            distance = centroids.apply ( lambda x : (np.sqrt((data-x)**2)).sum(axis = 0 ))
            labels = distances.idxmin(axis = 1 )
            centroids= data.groupby(labels).mean () 
        return labels, centroids

In [58]:
k = 5 
interation = 100 
model = k_mean ( k= k, interation = interation ) 
labels,_ = model.forward(data )

/tmp/ipykernel_13252/3663270666.py:9: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  centroid = self.data.apply(lambda x : float (x.sample()))

In [59]:
labels.head ()

0    3
1    3
2    3
3    3
4    2
dtype: int64